-- 新增宿主机内网穿透与反向隧道字段
ALTER TABLE "hosts" ADD COLUMN IF NOT EXISTS "tunnel_enabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "hosts" ADD COLUMN IF NOT EXISTS "target_host" TEXT NOT NULL DEFAULT '127.0.0.1';
ALTER TABLE "hosts" ADD COLUMN IF NOT EXISTS "target_port" INTEGER NOT NULL DEFAULT 8443;
